# Generated by Django 5.2 on 2025-05-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icon_name', models.CharField(choices=[('cat', 'Gato'), ('dog', 'Cachorro')], default='cat', help_text='Ícone para esta subcategoria', max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='loja.categoria')),
            ],
        ),
    ]
