# Generated by Django 5.2 on 2025-05-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(default=3, help_text='Escolha a subcategoria deste produto', on_delete=django.db.models.deletion.CASCADE, to='loja.subcategoria', verbose_name='Subcategoria'),
            preserve_default=False,
        ),
    ]
